name:                Checkr
version:             0.1.0.0
github:              "githubuser/Checkr"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Checkr#readme>

default-extensions:
  - DeriveGeneric
  - GeneralizedNewtypeDeriving
  - NoImplicitPrelude
  - OverloadedStrings
  - MultiParamTypeClasses

dependencies:
- base >= 4.7 && < 5
- protolude

library:
  source-dirs: src
  dependencies:
    - aeson
    - data-default-class
    - http-types
    - mtl
    - scotty
    - stm
    - text
    - validation

executables:
  Checkr-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Checkr

tests:
  Checkr-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -j4
    dependencies:
    - Checkr
    - hspec
